stages:
    - build
    - store

build:
    stage: build
    tags:
        - DPAD_dev
    script:
        - docker-compose -f docker-compose.yml build --no-cache kprod_services_api
        - docker-compose -f docker-compose.yml up --force-recreate -d kprod_services_api
    rules:
        - if: $CI_PIPELINE_SOURCE == "trigger" && $LOCAL_DEPLOY == "true"
        - when: manual

build-and-save:
    stage: store
    tags:
        - DPAD_dev
    script:
        - bash ./build.bash
    rules:
        - if: $CI_PIPELINE_SOURCE == "trigger" && $REMOTE_BUILD == "true"
        - when: manual
    environment:
        name: store
