version: '3.3'


networks:
  dpadsoftware_DPADSoftware:
    external: true

services:

  kprod_services_api:
    image: kprod_services_api
    container_name: kprod_services_api
    build:
      context: .
      dockerfile: ./docker/kprod_services
    command: sh -c "gunicorn src.use_cases.app:app --workers 4 --timeout 7200 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080 --max-requests=40"
    env_file:
      - ./docker.env
    ports:
      - "40000:8080"
    networks:
      - dpadsoftware_DPADSoftware

